name: CI Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.dev.txt
          pip install -r requirements.txt

      - name: Run pylint
        run: pylint --fail-under=10 coar_notify_validator

      - name: Run flake8
        run: flake8 coar_notify_validator

      - name: Run pytest
        run: pytest tests
